name: Publish
on:
  push:
    branches:
      - 'main'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: 'main'
          target_branch: 'gh-pages'
          commit_message_template: '[Automated] Merge {source_ref} into {target_branch}'